In [14]:
import numpy as np
import pandas as p
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import colors
from Bio import SeqIO
%matplotlib inline

In [11]:
primer_assignments = p.read_csv('diversity_check_pcr_primers.csv')
primer_assignments['sample_name'] = [pool+'_'+date for pool,date in zip(primer_assignments['Pool'].values,primer_assignments['Date'].values)]
primer_assignments['sample_counter'] = ['S74','S75','S76','S77','S78','S80','S81','S82','S83','S84']

In [12]:
primer_assignments

,Pool,Date,F_primer,R_primer,N_primer,S_primer,sample_name,sample_counter
0,74D-1,ND,F202,R307,N718,S521,74D-1_ND,S74
1,74D-1,041217,F203,R307,N719,S521,74D-1_041217,S75
2,74D-2,112217,F204,R307,N720,S521,74D-2_112217,S76
3,74D-6,112217,F205,R307,N721,S521,74D-6_112217,S77
4,74D-7,112217,F206,R307,N722,S521,74D-7_112217,S78
5,YP1,041217,F208,R307,N724,S521,YP1_041217,S80
6,YP1-B2-1,060217,F209,R307,N726,S521,YP1-B2-1_060217,S81
7,YP10,031717,F210,R307,N727,S521,YP10_031717,S82
8,YP12,031717,F211,R307,N728,S521,YP12_031717,S83
9,YP4,031717,F212,R307,N729,S521,YP4_031717,S84

In [15]:
primer_set = SeqIO.to_dict(SeqIO.parse('allCRs.fasta','fasta'))

In [27]:
print(str(primer_set['F201'].seq))
print(str(primer_set['F202'].seq))
print(str(primer_set['F201'].seq)[:6])
print(str(primer_set['F202'].seq)[:6])

print(str(primer_set['R301'].seq))
print(str(primer_set['R302'].seq))
print(str(primer_set['R301'].seq)[8:])
print(str(primer_set['R302'].seq)[8:])

CGATGTTTAATATGGA
ACAGTGTTAATATGGA
CGATGT
ACAGTG
AATTCGAGCGTATATA
AATTCGAGATAGAGCG
CGTATATA
ATAGAGCG

In [29]:
input_filename = 'diversitycheck.inp'

with open(input_filename,'w') as input_file:

    for index in range(len(primer_assignments.index)):
        s_primer = primer_assignments['S_primer'].values[index]
        n_primer = primer_assignments['N_primer'].values[index]
        f_primer = primer_assignments['F_primer'].values[index]
        r_primer = primer_assignments['R_primer'].values[index]
        sample_name = primer_assignments['sample_name'].values[index]
        sample_counter = primer_assignments['sample_counter'].values[index]

        multiplex_file = f'diversitycheck_{sample_name}_multiplex.txt'
        f_fasta = f'18032FL-38-{s_primer}{n_primer}_{sample_counter}_L001_R1_001.fastq.gz'
        r_fasta = f'18032FL-38-{s_primer}{n_primer}_{sample_counter}_L001_R2_001.fastq.gz'

        f_seq = str(primer_set[f_primer].seq)[:6]
        r_seq = str(primer_set[r_primer].seq)[8:]

        with open(multiplex_file,'w') as multiplex:
            multiplex.write(f'{sample_name}\t0\t0\t{f_seq}\t{r_seq}')

        input_file.write(f'{f_fasta}\t{r_fasta}\t{multiplex_file}\n')