In [1]:
import pandas as p
from datetime import date
import datetime

In [2]:


evolutions = {'Evo1D':{'IRAs':['1','2'],'Tor1Cyr1Gpb2':['1','2']},
              'Evo2D':{'Ira1 MIS':['1','2'],'Ira1 NON':['1','2']},
              'Evo3D':{'Ira1 MIS':['1','2','3'],'Ira1 NON':['1','2','3'],'Tor1Cyr1Gpb2':['1','2']}  }


starting_date = date(2019,4,16)
n_transfers = 31

all_labels = []

for transfer in range(n_transfers):
    for evolution in evolutions.keys():
        for genotype in evolutions[evolution].keys():
            for replicate in evolutions[evolution][genotype]:
                

                if '1' in evolution:
                    this_d = starting_date + datetime.timedelta(days=1*transfer)
                elif '2' in evolution:
                    this_d = starting_date + datetime.timedelta(days=2*transfer)
                elif '3' in evolution:
                    this_d = starting_date + datetime.timedelta(days=3*transfer)

                all_labels.append([evolution,genotype,'Rep'+str(replicate),'T'+str(transfer),transfer,this_d.isoformat()])
#                 {'evolution':evolution,
#                                    'genotype':genotype,
#                                    'replicate':'Rep'+str(replicate),
#                                    'transfer':'T_'+str(transfer),
#                                    'date':this_d.isoformat()},ignore_index=True)

In [4]:
label_df = p.DataFrame(all_labels,columns=['evolution','genotype','replicate','transfer','transfer_number','date'])

In [5]:
label_df = label_df.sort_values(['date','evolution','transfer_number','genotype','replicate'])

In [6]:
label_df = label_df.drop(['transfer_number'],axis=1)

In [7]:
label_df

    evolution      genotype replicate transfer        date
0       Evo1D          IRAs      Rep1       T0  2019-04-16
1       Evo1D          IRAs      Rep2       T0  2019-04-16
2       Evo1D  Tor1Cyr1Gpb2      Rep1       T0  2019-04-16
3       Evo1D  Tor1Cyr1Gpb2      Rep2       T0  2019-04-16
4       Evo2D      Ira1 MIS      Rep1       T0  2019-04-16
5       Evo2D      Ira1 MIS      Rep2       T0  2019-04-16
6       Evo2D      Ira1 NON      Rep1       T0  2019-04-16
7       Evo2D      Ira1 NON      Rep2       T0  2019-04-16
8       Evo3D      Ira1 MIS      Rep1       T0  2019-04-16
9       Evo3D      Ira1 MIS      Rep2       T0  2019-04-16
10      Evo3D      Ira1 MIS      Rep3       T0  2019-04-16
11      Evo3D      Ira1 NON      Rep1       T0  2019-04-16
12      Evo3D      Ira1 NON      Rep2       T0  2019-04-16
13      Evo3D      Ira1 NON      Rep3       T0  2019-04-16
14      Evo3D  Tor1Cyr1Gpb2      Rep1       T0  2019-04-16
15      Evo3D  Tor1Cyr1Gpb2      Rep2       T0  2019-04-16
16      Evo1D          IRAs      Rep1       T1  2019-04-17
17      Evo1D          IRAs      Rep2       T1  2019-04-17
18      Evo1D  Tor1Cyr1Gpb2      Rep1       T1  2019-04-17
19      Evo1D  Tor1Cyr1Gpb2      Rep2       T1  2019-04-17
32      Evo1D          IRAs      Rep1       T2  2019-04-18
33      Evo1D          IRAs      Rep2       T2  2019-04-18
34      Evo1D  Tor1Cyr1Gpb2      Rep1       T2  2019-04-18
35      Evo1D  Tor1Cyr1Gpb2      Rep2       T2  2019-04-18
20      Evo2D      Ira1 MIS      Rep1       T1  2019-04-18
21      Evo2D      Ira1 MIS      Rep2       T1  2019-04-18
22      Evo2D      Ira1 NON      Rep1       T1  2019-04-18
23      Evo2D      Ira1 NON      Rep2       T1  2019-04-18
48      Evo1D          IRAs      Rep1       T3  2019-04-19
49      Evo1D          IRAs      Rep2       T3  2019-04-19
..        ...           ...       ...      ...         ...
442     Evo3D      Ira1 MIS      Rep3      T27  2019-07-06
443     Evo3D      Ira1 NON      Rep1      T27  2019-07-06
444     Evo3D      Ira1 NON      Rep2      T27  2019-07-06
445     Evo3D      Ira1 NON      Rep3      T27  2019-07-06
446     Evo3D  Tor1Cyr1Gpb2      Rep1      T27  2019-07-06
447     Evo3D  Tor1Cyr1Gpb2      Rep2      T27  2019-07-06
456     Evo3D      Ira1 MIS      Rep1      T28  2019-07-09
457     Evo3D      Ira1 MIS      Rep2      T28  2019-07-09
458     Evo3D      Ira1 MIS      Rep3      T28  2019-07-09
459     Evo3D      Ira1 NON      Rep1      T28  2019-07-09
460     Evo3D      Ira1 NON      Rep2      T28  2019-07-09
461     Evo3D      Ira1 NON      Rep3      T28  2019-07-09
462     Evo3D  Tor1Cyr1Gpb2      Rep1      T28  2019-07-09
463     Evo3D  Tor1Cyr1Gpb2      Rep2      T28  2019-07-09
472     Evo3D      Ira1 MIS      Rep1      T29  2019-07-12
473     Evo3D      Ira1 MIS      Rep2      T29  2019-07-12
474     Evo3D      Ira1 MIS      Rep3      T29  2019-07-12
475     Evo3D      Ira1 NON      Rep1      T29  2019-07-12
476     Evo3D      Ira1 NON      Rep2      T29  2019-07-12
477     Evo3D      Ira1 NON      Rep3      T29  2019-07-12
478     Evo3D  Tor1Cyr1Gpb2      Rep1      T29  2019-07-12
479     Evo3D  Tor1Cyr1Gpb2      Rep2      T29  2019-07-12
488     Evo3D      Ira1 MIS      Rep1      T30  2019-07-15
489     Evo3D      Ira1 MIS      Rep2      T30  2019-07-15
490     Evo3D      Ira1 MIS      Rep3      T30  2019-07-15
491     Evo3D      Ira1 NON      Rep1      T30  2019-07-15
492     Evo3D      Ira1 NON      Rep2      T30  2019-07-15
493     Evo3D      Ira1 NON      Rep3      T30  2019-07-15
494     Evo3D  Tor1Cyr1Gpb2      Rep1      T30  2019-07-15
495     Evo3D  Tor1Cyr1Gpb2      Rep2      T30  2019-07-15

[496 rows x 5 columns]

In [8]:
label_df.to_csv('EvolutionOfTheFront_freezer_labels.csv',index=False)

In [9]:
label_df

    evolution      genotype replicate transfer        date
0       Evo1D          IRAs      Rep1       T0  2019-04-16
1       Evo1D          IRAs      Rep2       T0  2019-04-16
2       Evo1D  Tor1Cyr1Gpb2      Rep1       T0  2019-04-16
3       Evo1D  Tor1Cyr1Gpb2      Rep2       T0  2019-04-16
4       Evo2D      Ira1 MIS      Rep1       T0  2019-04-16
5       Evo2D      Ira1 MIS      Rep2       T0  2019-04-16
6       Evo2D      Ira1 NON      Rep1       T0  2019-04-16
7       Evo2D      Ira1 NON      Rep2       T0  2019-04-16
8       Evo3D      Ira1 MIS      Rep1       T0  2019-04-16
9       Evo3D      Ira1 MIS      Rep2       T0  2019-04-16
10      Evo3D      Ira1 MIS      Rep3       T0  2019-04-16
11      Evo3D      Ira1 NON      Rep1       T0  2019-04-16
12      Evo3D      Ira1 NON      Rep2       T0  2019-04-16
13      Evo3D      Ira1 NON      Rep3       T0  2019-04-16
14      Evo3D  Tor1Cyr1Gpb2      Rep1       T0  2019-04-16
15      Evo3D  Tor1Cyr1Gpb2      Rep2       T0  2019-04-16
16      Evo1D          IRAs      Rep1       T1  2019-04-17
17      Evo1D          IRAs      Rep2       T1  2019-04-17
18      Evo1D  Tor1Cyr1Gpb2      Rep1       T1  2019-04-17
19      Evo1D  Tor1Cyr1Gpb2      Rep2       T1  2019-04-17
32      Evo1D          IRAs      Rep1       T2  2019-04-18
33      Evo1D          IRAs      Rep2       T2  2019-04-18
34      Evo1D  Tor1Cyr1Gpb2      Rep1       T2  2019-04-18
35      Evo1D  Tor1Cyr1Gpb2      Rep2       T2  2019-04-18
20      Evo2D      Ira1 MIS      Rep1       T1  2019-04-18
21      Evo2D      Ira1 MIS      Rep2       T1  2019-04-18
22      Evo2D      Ira1 NON      Rep1       T1  2019-04-18
23      Evo2D      Ira1 NON      Rep2       T1  2019-04-18
48      Evo1D          IRAs      Rep1       T3  2019-04-19
49      Evo1D          IRAs      Rep2       T3  2019-04-19
..        ...           ...       ...      ...         ...
442     Evo3D      Ira1 MIS      Rep3      T27  2019-07-06
443     Evo3D      Ira1 NON      Rep1      T27  2019-07-06
444     Evo3D      Ira1 NON      Rep2      T27  2019-07-06
445     Evo3D      Ira1 NON      Rep3      T27  2019-07-06
446     Evo3D  Tor1Cyr1Gpb2      Rep1      T27  2019-07-06
447     Evo3D  Tor1Cyr1Gpb2      Rep2      T27  2019-07-06
456     Evo3D      Ira1 MIS      Rep1      T28  2019-07-09
457     Evo3D      Ira1 MIS      Rep2      T28  2019-07-09
458     Evo3D      Ira1 MIS      Rep3      T28  2019-07-09
459     Evo3D      Ira1 NON      Rep1      T28  2019-07-09
460     Evo3D      Ira1 NON      Rep2      T28  2019-07-09
461     Evo3D      Ira1 NON      Rep3      T28  2019-07-09
462     Evo3D  Tor1Cyr1Gpb2      Rep1      T28  2019-07-09
463     Evo3D  Tor1Cyr1Gpb2      Rep2      T28  2019-07-09
472     Evo3D      Ira1 MIS      Rep1      T29  2019-07-12
473     Evo3D      Ira1 MIS      Rep2      T29  2019-07-12
474     Evo3D      Ira1 MIS      Rep3      T29  2019-07-12
475     Evo3D      Ira1 NON      Rep1      T29  2019-07-12
476     Evo3D      Ira1 NON      Rep2      T29  2019-07-12
477     Evo3D      Ira1 NON      Rep3      T29  2019-07-12
478     Evo3D  Tor1Cyr1Gpb2      Rep1      T29  2019-07-12
479     Evo3D  Tor1Cyr1Gpb2      Rep2      T29  2019-07-12
488     Evo3D      Ira1 MIS      Rep1      T30  2019-07-15
489     Evo3D      Ira1 MIS      Rep2      T30  2019-07-15
490     Evo3D      Ira1 MIS      Rep3      T30  2019-07-15
491     Evo3D      Ira1 NON      Rep1      T30  2019-07-15
492     Evo3D      Ira1 NON      Rep2      T30  2019-07-15
493     Evo3D      Ira1 NON      Rep3      T30  2019-07-15
494     Evo3D  Tor1Cyr1Gpb2      Rep1      T30  2019-07-15
495     Evo3D  Tor1Cyr1Gpb2      Rep2      T30  2019-07-15

[496 rows x 5 columns]